#!/bin/bash

adb devices
read -p "Press [Enter] to continue..."

PACKAGES=(
"com.amazon.appmanager"
"com.android.browser"
"com.android.thememanager"
"com.android.wallpaper.livepicker"
"com.facebook.services"
"com.facebook.system"
"com.facebook.appmanager"
"com.miui.compass"
"com.miui.notes"
"com.mi.android.globalminusscreen"
"com.snapchat.android"
"com.funnypuri.client"
"com.google.android.apps.tachyon"
"com.google.android.feedback"
"com.king.candycrushsaga"
"com.mintgames.schuman.ablock"
"com.google.android.googlequicksearchbox"
"com.google.android.marvin.talkback"
"com.google.android.music"
"com.google.android.syncadapters.calendar"
"com.google.android.syncadapters.contacts"
"com.google.android.tts"
"com.xiaomi.midrop"
"com.xiaomi.mipicks"

"com.mintgames.zentriple3d"
"cn.wps.xiaomi.abroad.lite"
"cn.wps.moffice_eng"

"com.facebook.services"
"com.facebook.system"
"com.facebook.appmanager"
"com.alibaba.aliexpresshd"
"com.android.providers.downloads.ui"
"com.netflix.partner.activation"
"com.zhiliaoapp.musically"
"ru.yandex.searchplugin"
"com.google.android.music"
"com.google.android.videos"
"com.linkedin.android"
"com.xiaomi.payment"
"com.xiaomi.scanner"
"com.miui.player"
"com.duokan.phone.remotecontroller"
"com.duokan.phone.remotecontroller.peel.plugin"
"com.google.android.apps.tachyon"

"com.mipay.wallet.in"
"app.buzz.share"
"com.miui.miservice"
"com.mi.android.globalpersonalassistant"
"com.mi.android.globalpersonalassistant"
"com.mi.android.globalpersonalassistant"
  

"com.mi.android.globalpersonalassistant"
"com.mi.dlabs.vr"
"com.mi.globalTrendNews"
"com.mi.global.bbs"
"com.mi.global.shop"
"com.micredit.in"
"com.milink.service"
"com.mipay.wallet.id"
"com.mipay.wallet.in"
"com.miui.analytics"
"com.miui.bugreport"
"com.miui.cloudbackup"
"com.miui.cloudservice"
"com.miui.cloudservice.sysbase"
"com.miui.micloudsync"
"com.miui.hybrid"
"com.miui.hybrid.accessory"
"com.miui.klo.bugreport"
"com.miui.miservice"
"com.miui.msa.global"
"com.miui.player"
"com.miui.providers.weather"
"com.miui.screenrecorder"
"com.miui.translationservice"
"com.miui.translation.kingsoft"
"com.miui.translation.xmcloud"
"com.miui.translation.youdao"
"com.miui.touchassistant"
"com.miui.userguide"
"com.miui.videoplayer"
"com.miui.virtualsim"
"com.miui.weather2"
"com.miui.yellowpage"
"com.netflix.partner.activation"
)

for PACKAGE in "${PACKAGES[@]}"; do
    adb shell pm uninstall "$PACKAGE"
    adb shell pm uninstall -k --user 0 "$PACKAGE"
done
